name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main

jobs:
  build:
    name: Performs the build and Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew check test

    - name: Collect artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Unit Test Results
        path: |
          build/reports/tests/test

  approve:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Approve Step
    needs: build
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: manual approve
        run: |
          echo "Manually approved"

  integration-tests:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Run Integration Tests
    needs: approve
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew integrationTest

      - name: Collect artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Integration Test Results
          path: |
            build/reports/tests/integrationTest
